### ISSUE TITLE
[Help] MVI to disk

### ISSUE THREAD

**Issue by oneingan** [ptribble/mvi#3]
Hi again Peter,
I have some working systems with MVI.iso or MVI running trough PXE. All works well. I am very satisfied with them. But now I have some systems with very little RAM and big disk so I would like to run MVI direct on disk.

Maybe boot PXE and dump the ISO to the disk.

Can you give me some guidelines to achieve this?
Thanks in advance.

**Comment by oneingan** [comment]
I was thinking about mvi.sh creating some raw disk image instead of the ISO and then make dd to physical disk prior to boot. Do you think that it will work?

(I have working something similar but in linux-world)

**Comment by oneingan** [comment]
Hello again. I'm keeping investigating. Now I have mixed mvi.sh with ufs_install.sh and can get a working MVI disk.

Then convert .vdi to raw disk image and make dd from a bootcd to physical disk. It works!

But now I've discovered that opensolaris have a vdiskadm that creates file backed block device raw images. I miss a lot this package in Tribblix. Any chance to port? Any other way to achieve my target (maybe with lofiadm)?

Thanks again.

**Comment by ptribble** [comment]
As you've probably discovered from looking at ufs_install.sh, basic installation wouldn't be difficult - it's just:
1. Partition disk, create filesystem
2. Copy the boot archive into place
3. Install grub

The tricky part here is that typically an mvi image wouldn't contain the tools necessary to do that. So it might be necessary to boot a standard Tribblix image to do the installation.

Or construct a custom mvi image that just has the appropriate tools, and has one or more mvi boot archives included in the ISO so it can install them to disk. That sounds like it would be worth doing, so I might try to make that work.

**Comment by oneingan** [comment]
Hello and thanks a lot for your help.

I've build a MVI ISO with a script that makes steps 1, 2 and 3. It was really easy and works perfectly.

But I've some doubt, I'm running boot_archive located in hard disk but really boot_archive always run as a ramdisk, so I'm also limited by RAM size, am I correct?

So, the only way is also copy boot_archive contents to disk partition and make all the bootenv, vfstab and grub stuff?

**Comment by ptribble** [comment]
You're always going to have some sort of boot archive - on a normal illumos system it will be 20M or so compressed, that just contains enough drivers to set up the disk and mount it.

With MVI, yes, you're always running as a ramdisk. But that's likely to be pretty efficient - everything in the image is there because you're using it, so it would be read from disk into memory in any case. You're likely to use less memory than booting from disk, as there's a lot of extra setup and code needed to make that work.

All my very minimal memory experiments were done using MVI, down to 48M of RAM.
