### ISSUE TITLE
Hi ptribble, what about something like Tiny Core Tribblix?

### ISSUE THREAD

**Issue by hoper-a11y** [ptribble/mvi#5]
The idea is similar to Tiny Core Linux. I'm very impressed to see such a small Illumos. I'm interested to do something similar to you but I lacked the knowledge so I still can't. Is there anything like menuconfig of the Linux kernel to allow us cherry picking which components we needed? As I read the docs I found nothing like that. Is it the reason why you have to remove components from an installed system to archive the goal?

I don't know that we could remove zfs from Illumos after all. I used to think zfs is an inseparable part of Illumos. Turned out to be wrong. I always want to build an Illumos distro that looked like classic BSD (OpenBSD, NetBSD) and Linux, no ZFS, no zones, no fancy features... just a plain old Unix-like system. I know Tribblix is the most close to that. But I seriously need a proper package management with proper dependency handling. I know you will not change your decision. So I turned my self to the ravenports project, hoping them could fill the missing piece but they currently have trouble with FreeBSD's pkg. My efforts go to nowhere. The day I could have my distro up and running is still far :(

**Comment by ptribble** [comment]
To follow up, the way illumos/Solaris is built there's no equivalent to menuconfig. Rather than configurinbg a static kernel at build time, we have a dynamic modular kernel that can be configured at runtime. In practice, in normal operation you install all the kernel modules and drivers and it only loads the ones it needs. Any separation is done via packaging, and even then that doesn't help much.

Partly because of this, there's no real understanding of dependencies between kernel modules, and no incentive to minimise dependencies, as a normal general purpose system will need almost all the modules anyway. A lot of the work was to try deleting a module and see if the system still worked.

There's a similar problem in userland, with a lot more libraries being pulled in to satisfy dependencies than is ideal. On virtually all systems, it doesn't matter, which is why nobody else worries about it.
